### ISSUE TITLE
DriveItemRequestBuilder.CreateUploadSession(DriveItemUploadableProperties) fails

### ISSUE THREAD

**Issue by ajweber** [microsoftgraph/msgraph-sdk-serviceissues#17]
As documented in example test method, part of the source was commented-out because it fails the test (questionable whether this is a valid test suite here?), OneDriveTests.OneDriveUploadLargeFile, it is currently not possible to specify basic properties when uploading a new DriveItem (file).

As a partial workaround, one can update the Description after successful creation of the document.  However, it would be extremely beneficial to be able to specify the document's actual CreationDate, ModifiedDate and other FileSystemInfo per the commented-out example.

### Expected behavior
Creating an UploadSession with the optional DriveItemUploadableProperties parameter does not throw an exception and actually populates the specified properties of the DriveItem during the creation.

### Actual behavior
Exception Thrown
`Microsoft.Graph.ServiceException: Code: invalidRequest
Message: The request is malformed or incorrect.

Inner error

   at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()`

### Steps to reproduce the behavior
Simply un-comment out the lines in OneDriveTests.cs and attempt to upload a new document/file with a Description and actual File CreationDateTime.

**Comment by petrhollayms** [comment]
Thank you for reporting this issue. This appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*] tags, that way it will get routed to the appropriate team for them to triage:  
 
https://aka.ms/msgraphsupport or directly https://aka.ms/askgraph 

For now, we will close the issue on our side but feel free to open it in the relevant repository if you think the issue is specific to SDK. 
Please let us know if this helps! 

Note: We will close this repository on April 19, 2024.
