### ISSUE TITLE
UnknownError during request to Microsoft.Graph API  while updating subscription.

### ISSUE THREAD

**Issue by Yury3cx** [microsoftgraph/msgraph-sdk-serviceissues#29]
**Describe the bug**
Following code produces sometime "UnknownError":

        public async Task<IList<Subscription>> GetSubscriptionsAsync(CancellationToken token)
        {
            var subscriptions = new List<Subscription>();
            var request = _client.Subscriptions.Request();
            while (request != null)
            {
                var response = await request.GetAsync(token);
                subscriptions.AddRange(response);
                request = response.NextPageRequest;
            }
            return subscriptions;
        }

**To Reproduce**
Reproduced for 70% of cases.

**Expected behavior**
Request will return expected result.

**Screenshots**
We get following error: 
2020/08/25 05:00:31.629|26499|0049|Erro|Error running Office365 synchronization: Code: UnknownError
Inner error:
    AdditionalData:
    date: 2020-08-25T03:00:31
    request-id: b91dfe7d-3ed8-454e-b5ca-88ad02210943
ClientRequestId: b91dfe7d-3ed8-454e-b5ca-88ad02210943

2020/08/25 05:00:31.810|26499|0049|Erro|FullStackTrace: at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.GraphServiceSubscriptionsCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at Integration.Office365.Notifications.Office365SubscriptionManager.GetSubscriptionsAsync(CancellationToken token)
   at Integration.Office365.Synchronization.Office365SyncExecutor.ExecuteFullSynchronizationAsync(License license, Office365Configuration configuration, CancellationToken token)

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
This code was fully functional more than 2 two years, but approximately 1 month ago a lot of our customers begin to complain.

**Comment by petrhollayms** [comment]
Thank you for reporting this issue. This appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*] tags, that way it will get routed to the appropriate team for them to triage:  
 
https://aka.ms/msgraphsupport or directly https://aka.ms/askgraph 

For now, we will close the issue on our side but feel free to open it in the relevant repository if you think the issue is specific to SDK. 
Please let us know if this helps! 

Note: We will close this repository on April 19, 2024.
