### ISSUE TITLE
transitiveMemberOfAsGroup fails

### ISSUE THREAD

**Issue by davidkarlsen** [microsoftgraph/msgraph-sdk-serviceissues#37]
### Expected behavior

Lookup of groups should work:

```
var groups =
          graphServiceClient.users(optionalUser.get().id).transitiveMemberOfAsGroup().buildRequest().get();
```

### Actual behavior

```
Internal server error:
"error": {
    "code": "InternalServerError",
    "message": "A resource of type 'microsoft.graph.directoryRole' was found in a resource set that otherwise has entries of type 'microsoft.graph.group'. In OData, all entries in a resource set must have a common base type.",
    "innerError": {
      "date": "2020-12-04T00:12:29",
      "request-id": "93c6c39e-2b1c-49c4-886e-189215f7bbd5",
      "client-request-id": "e70f57f9-97a3-4980-9f2e-50decfc6becd"
    }
  }
```

```
[Some information was truncated for brevity, enable debug logging for more details]
        at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:490)
        at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:503)
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:423)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
        at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:92)
        at com.microsoft.graph.requests.extensions.GroupCollectionWithReferencesRequest.get(GroupCollectionWithReferencesRequest.java:55)
```

```
GET https://graph.microsoft.com/v1.0/users/XXXXX/transitiveMemberOf/microsoft.graph.group
SdkVersion : graph-java/v2.4.1
Authorization : [PII_REDACTED]
```

**Comment by baywet** [comment]
Hey @davidkarlsen 
Thanks for reaching out. After giving it a try it appears the service is not behaving like it should (according to the metadata).
The best thing for you to do is to contact [the support](https://developer.microsoft.com/en-us/graph/support) so the service engineers can investigate and solve the issue.
I'm leave this issue open for visibility but transferring it to the service issues repository.

**Comment by davidkarlsen** [comment]
I don't have access to the enterprise agreement in order to open a support case so I guess that's a dead end...

**Comment by baywet** [comment]
I have created the incident 217025424 as I can reproduce the issue on my dev tenant, but incidents created by internal teams that are not linked to tickets from customers usually get a lesser priority.

**Comment by baywet** [comment]
Hi @davidkarlsen 
I got a response from the service team, the request will work using the Mezzo APIs
Http:
```
GET https://graph.microsoft.com/v1.0/me/transitiveMemberOf/microsoft.graph.group?$count=true
ConsistencyLevel: eventual
```

```Java
final List<Option> consistencyLevelOptions = Arrays.asList(new HeaderOption("ConsistencyLevel", "eventual"));
final GroupCollectionPage groups = graphServiceClient.users(optionalUser.get().id).transitiveMemberOfAsGroup().buildRequest(consistencyLevelOptions).count().get();
```

They are still working on fixing the response when using the "classic" identity service so it returns a proper error message.
Thanks for the patience

**Comment by davidkarlsen** [comment]
@baywet Any update to this issue?

**Comment by baywet** [comment]
@davidkarlsen thanks for the nudge. A bug has been logged with the team responsible back in march, and the incident closed. No activity since. 
(for me: id div, id 1271046)

**Comment by davidkarlsen** [comment]
> @davidkarlsen thanks for the nudge. A bug has been logged with the team responsible back in march, and the incident closed. No activity since.
> (for me: id div, id 1271046)

_and the incident closed_ - what does that mean? No fix will be released?

**Comment by baywet** [comment]
Hey @davidkarlsen 
Thanks for your patience. I finally heard from the service team, they put together a fix for that. I don't have an ETA for availability on the public cloud, but I'm trying to get that information as well.

**Comment by baywet** [comment]
Hi @davidkarlsen ,
The service team has confirmed to me the deployment of the fix is completed to all pubic clouds.
Thanks again for your patience on that matter!
Closing

**Comment by davidkarlsen** [comment]
Yay, thanks for reminding me... :-)
